### ISSUE TITLE
Update chord

### ISSUE THREAD

**Issue by craffel** [craffel/mir_eval#81]
`mir_eval.chord` needs the following changes to be up-to-date with the structure/conventions of the other modules, before 0.1 gets released:
- [x] Separate out scoring function #63 
- [x] Make `evaluate` function #70
- [x] Move `evaluate_file_pair` to the evaluator #62 
- [x] Docstring audit/reformatting #69 
- [x] Evaluator should output json and match other evaluator's structure #8 
- [x] Regression/unit tests should match other tests' structure and should use `evaluate` and not `METRICS` #73 
- [x] Remove `METRICS` dictionary #54

~~chord.validate should use util.validate_intervals~~
